<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>9c2031b2-8e84-4928-a610-17c9c6edae89</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
  <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
  <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
  <PackageReference Include="MassTransit" Version="8.2.5" />
  <PackageReference Include="MassTransit.RabbitMQ" Version="8.2.5" />
  <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.2" />
  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.2">
    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    <PrivateAssets>all</PrivateAssets>
  </PackageReference>
  <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.3" />
  <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
  <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.6.0" />
</ItemGroup>

    

</Project>
